from .blob_to_process_queue_message import  BlobToProcessQueueMessage
from .image_prediction_result import ImagePredictionResult
from .visio_detector_http_request import VisioDetectorHttpRequest
from .ssd_rcnn_detector_result import SSDDetectorResult